### ISSUE TITLE
Verifier error on Linux 5.x (arm64)

### ISSUE THREAD

**Issue by unixisevil** [ti-mo/conntracct#36]
Hi  @ti-mo ,  i have an arm64  device running linux  kernel  5.0.0,   i  build  my 5.0.0 version ebpf probe, 
but  an  error occurred during   initialize pipeline:
```bash
Error: initialize pipeline: initializing BPF probe: loading probe 5.0.0: creating collection: program kretprobe____nf_ct_refresh_acct: can't load program: invalid argument
```
i  haven't a clue about the problem,  current kernel missing  some necessary configuration ?

**Comment by ti-mo** [comment]
Hi @unixisevil, thanks for reporting! I'm currently not actively working on this project, and I don't have an arm64 machine to test this on.

This is likely an eBPF verifier error; is there any more output after this? Could you try upgrading the `cilium/ebpf` dependency on your local checkout to 0.4.0 or master? The version that's currently used here might be lacking the necessary endianness support.

**Comment by unixisevil** [comment]
> This is likely an eBPF verifier error; is there any more output after this?

no other output 

> Could you try upgrading the cilium/ebpf dependency on your local checkout to 0.4.0 or master? 

after update cilium/ebpf  lib to  0.4.0,  prev  error disappear, but  another  popped up: 
```bash
Error: initialize pipeline: initializing BPF probe: loading probe 5.0.0: creating collection: map currct: map create: RLIMIT_MEMLOCK may be too low: operation not permitted
```
i  run it with root  account, 'operation not permitted' ?

**Comment by ti-mo** [comment]
Ah, right. conntracct was [built against a branch on my fork of `cilium/ebpf`](https://github.com/ti-mo/ebpf/tree/conntracct-patches), which contains a few patches that aren't included upstream (yet). You could try your hand at rebasing it yourself.

**Comment by ti-mo** [comment]
@unixisevil I managed to do a quick rebase of the branch, please try it out. I've removed the commit that automatically sets rlimit, so you'll temporarily have to add that somewhere to conntracct itself (https://github.com/ti-mo/ebpf/blob/conntracct-patches/examples/kprobe/main.go#L33-L40). Just plunk it in `main()`, doesn't matter. Good luck!

**Comment by unixisevil** [comment]
@ti-mo , thanks,  i' ll try it  on Tuesday,  arm device not at hand

**Comment by unixisevil** [comment]
@ti-mo ,  I already update  `cilium/ebpf`  point at  your `conntracct-patches`  branch, add `Setrlimit` call  in `main()`  like this

go.mod:
```go
replace github.com/cilium/ebpf => github.com/ti-mo/ebpf v0.0.0-20210402140228-f520d9212011
```
main.go:
```go
if err := unix.Setrlimit(unix.RLIMIT_MEMLOCK, &unix.Rlimit{
		Cur: unix.RLIM_INFINITY,
		Max: unix.RLIM_INFINITY,
	}); err != nil {
		log.Fatalf("failed to set temporary rlimit: %v", err)
	}
}
cmd.Execute()
```
but  same  invalid argument  error:
```bash
Error: initialize pipeline: initializing BPF probe: loading probe 5.0.0: creating collection: program kretprobe____nf_ct_refresh_acct: load program: invalid argument
```

**Comment by unixisevil** [comment]
@ti-mo ,  I already update  `cilium/ebpf`  point at  your `conntracct-patches`  branch, add `Setrlimit` call  in `main()`  like this

go.mod:
```go
replace github.com/cilium/ebpf => github.com/ti-mo/ebpf v0.0.0-20210402140228-f520d9212011
```
main.go:
```go
if err := unix.Setrlimit(unix.RLIMIT_MEMLOCK, &unix.Rlimit{
		Cur: unix.RLIM_INFINITY,
		Max: unix.RLIM_INFINITY,
	}); err != nil {
		log.Fatalf("failed to set temporary rlimit: %v", err)
	}
}
cmd.Execute()
```
but  same  invalid argument  error:
```bash
Error: initialize pipeline: initializing BPF probe: loading probe 5.0.0: creating collection: program kretprobe____nf_ct_refresh_acct: load program: invalid argument
```

**Comment by ti-mo** [comment]
@unixisevil Thanks for trying it out. This seems to fail in a similar way than https://github.com/cilium/ebpf/issues/266. Will close this for now, as this looks like we have some work to do on the library, and I'm not sure what's causing this at the moment.
