### ISSUE TITLE
Boottime needs to be recalculated on unsuspend

### ISSUE THREAD

**Issue by ti-mo** [ti-mo/conntracct#9]
`pkg/boottime` can make an estimation of the boot time of the machine based on `time.Now()` and the kernel timestamp. When a machine is suspended, the kernel timestamp does not progress, causing events to be inserted in the past.

We need to figure out some way to reconcile kernel time with wall time, either continuously or on unsuspend. eg. `time.Now()` every second that sends an event when it detects a time jump (much) larger than the intervall.

**Comment by dominikh** [comment]
Could we use the `stop` timestamp of a flow in the destroy event as a way of recognizing desync of real time and kernel time? Under normal operation, the flow's stop time and the event's kernel time + the boot offset should be within nanoseconds of each other. If they're apart by a significant amount, our base is no longer correct.

Of course that depends on a) the time extension to be available b) flows actually being destroyed.

**Comment by ti-mo** [comment]
It could be one of multiple ways of determining drift, but it depends on destroy events coming in. There might simply not be any destroy events.

My current plan is to have `pkg/boottime` sitting on its own OS thread permanently (minimizing Go scheduler jitter), trying to determine the boottime continuously, once a second or so. That should be good enough for now.

This means our reference boottime could skip around a couple of nanoseconds on every update, but that can be countered by keeping the last X results in an array and calculating some sort of average everytime a new reference timestamp comes in.
